---
driver:
  name: vagrant
  network: 
    - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}] 
    - ["forwarded_port", {guest: 80, host: 80, auto_correct: true}] 

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: debian-8.2
  - name: opensuse-13.2

suites:
  - name: default
    run_list:
      - recipe[caddy::default]
    attributes:
      caddy:
        features:
          - cors
          - git
        email: caddy@example.com
        hosts: 
          localhost:8080:
          localhost:
            log: localhost.log
