---
driver:
  name: vagrant
  network: 
    - ["forwarded_port", {guest: 8080, host: 8080}] 
    - ["forwarded_port", {guest: 80, host: 80}] 

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[caddy::default]
    attributes:
      caddy:
        features:
          - cors
          - git
        email: caddy@example.com
        # you cannot define two hosts but only one is a hash, there must at least be one key
        hosts: 
          localhost:8080:
            tls: 'off'
          localhost:
            log: localhost.log
