---
driver:
  name: vagrant
  network: 
    - ["forwarded_port", {guest: 8080, host: 8080}] 

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[caddy::default]
    attributes:
